#gpu setting 
gpu_devices: 0 #[0,1,2,3,4,5,6,7]

# Input/Output/Name
data: /mnt/AI/Latex/LaTeX-OCR/pix2tex/model/dataset/train.pkl
valdata: /mnt/AI/Latex/LaTeX-OCR/pix2tex/model/dataset/valid.pkl
tokenizer: /mnt/AI/Latex/LaTeX-OCR/pix2tex/model/dataset/tokenizer.json
#output_path: "outputs"
model_path: "checkpoints"
load_chkpt: null
save_freq: 1 # save every epoch
name: "pix2tex-dennis"

#wandb: setting 
wandb: True 
wandb-project: pix2tex-dennis 

# Training parameters
epochs: 10
batchsize: 16
micro_batchsize: -1

# Testing parameters
testbatchsize: 16 # 20
valbatches: 16 # 100
temperature: 0.2

# Optimizer configurations
optimizer: "Adam"
scheduler: "StepLR"
lr: 0.001
gamma: 0.9995
lr_step: 30
betas:
- 0.9
- 0.999


# Parameters for model architectures
max_width: 672
max_height: 192
min_width: 32
min_height: 32
channels: 1
patch_size: 16 #32
# Encoder / Decoder
dim: 256 #128
backbone_layers:
- 2
- 3
- 7
encoder_depth: 4
num_layers: 4
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
heads: 8
num_tokens: 8000
max_seq_len: 512
encoder_structure: hybrid

# Other
seed: 42
id: null
sample_freq: 1000
test_samples: 5
debug: false
pad: false

# Token ids
pad_token: 0
bos_token: 1
eos_token: 2